sudo: required
service:
  - docker

before_install:
  - docker build -t rickchiu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rickchiu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-247983335540"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
